"""Local dashboard: a small JSON API plus the single-page UI that drives it.

Bound to loopback by default. The API still validates every path it is asked to
read or reveal against the masters root, because "it's only localhost" is how
browsers on the same machine get to read arbitrary files.
"""

from __future__ import annotations

import json
import math
import mimetypes
import os
import secrets
import socket
import subprocess
import threading
import webbrowser
from dataclasses import dataclass
from http import HTTPStatus
from http.server import BaseHTTPRequestHandler, ThreadingHTTPServer
from pathlib import Path
from typing import Any, Callable
from urllib.parse import parse_qs, urlparse

from .channels import InvalidChannel, parse_channel
from .config import Config
from .exports import MANIFEST_NAME, PUBLISHED_EXPORTS
from .pipeline import Pipeline
from .schema import ConfigError
from .snapshot import SnapshotRequest
from .util import LOG, slugify

STATIC_DIR = Path(__file__).resolve().parent / "static"

# Files the browser may fetch out of a session directory. Everything else --
# masters, proxies, the .ts working copies -- is many gigabytes and has no
# business travelling through this server.
# `.log` is deliberately absent: streamlink debug output is written to it
# verbatim, which can include configured header values, and it has no
# editorial use. Read it from disk if you need it.
READABLE_SUFFIXES = {".md", ".txt", ".json", ".srt", ".csv"}
MAX_READABLE_BYTES = 8 * 1024 * 1024

# The dashboard only ever sends small JSON objects; anything larger is a mistake
# or an attempt to exhaust memory on an unauthenticated endpoint.
MAX_BODY_BYTES = 256 * 1024

# A Windows filename component is limited to 255 UTF-16 code units. Snapshot
# names are free-form input that later becomes one component, so cap it well
# below that after reserving room for the channel, session, clocks and token.
MAX_SNAPSHOT_NAME_UNITS = 120
WINDOWS_FILENAME_UNITS = 255
SNAPSHOT_SUFFIX_RESERVE = len("_000000000000_235959_ffff.mp4")

# An HTTP client must not be able to occupy unbounded threads or keep an admitted
# thread forever by slowly sending a request. The socket timeout is an inactivity
# backstop; the phase deadlines are absolute and also stop byte-at-a-time clients.
MAX_CONCURRENT_HANDLERS = 32
SOCKET_TIMEOUT_SECONDS = 10.0
HEADER_DEADLINE_SECONDS = 10.0
BODY_DEADLINE_SECONDS = 20.0

# Hostnames a browser may legitimately use to reach a loopback-bound server.
ALLOWED_HOSTS = {"127.0.0.1", "localhost", "::1"}

# These are generated by the pipeline, rather than every text-like file that
# happens to have been placed under masters_root. `session.json`, recorder logs,
# and arbitrary notes are intentionally not browser-readable.
TRANSCRIPT_OUTPUT_NAMES = frozenset({
    *PUBLISHED_EXPORTS,
    MANIFEST_NAME,
    "words.json",
    "rundown.md",
    "edit.md",
})
SESSION_OUTPUT_NAMES = frozenset({"index.md"})
SNAPSHOT_OUTPUT_NAMES = frozenset({"snapshots.json"})


class ApiError(Exception):
    def __init__(self, message: str, status: int = HTTPStatus.BAD_REQUEST) -> None:
        super().__init__(message)
        self.status = status


@dataclass(frozen=True)
class RegisteredArtifact:
    session_id: str
    path: Path
    resolved: Path


class ArtifactRegistry:
    """Server-owned lookup for opaque, stable-for-this-process artifact IDs."""

    def __init__(self) -> None:
        self._lock = threading.Lock()
        self._by_id: dict[str, RegisteredArtifact] = {}
        self._by_path: dict[tuple[str, Path], str] = {}

    def register(self, session_id: str, path: Path, resolved: Path) -> str:
        key = (session_id, path)
        with self._lock:
            artifact_id = self._by_path.get(key)
            if artifact_id is None:
                artifact_id = secrets.token_urlsafe(24)
                self._by_path[key] = artifact_id
            self._by_id[artifact_id] = RegisteredArtifact(
                session_id=session_id, path=path, resolved=resolved)
            return artifact_id

    def get(self, artifact_id: str) -> RegisteredArtifact | None:
        with self._lock:
            return self._by_id.get(artifact_id)


class BoundedThreadingHTTPServer(ThreadingHTTPServer):
    """Threading server with admission control before a handler is spawned."""

    daemon_threads = True

    def __init__(self, server_address: tuple[str, int], handler: type,
                 *, max_handlers: int = MAX_CONCURRENT_HANDLERS) -> None:
        if max_handlers < 1:
            raise ValueError("max_handlers must be at least 1")
        self.max_concurrent_handlers = max_handlers
        self._handler_slots = threading.BoundedSemaphore(max_handlers)
        self._active_lock = threading.Lock()
        self._active_handlers = 0
        super().__init__(server_address, handler)

    @property
    def active_handlers(self) -> int:
        with self._active_lock:
            return self._active_handlers

    def process_request(self, request: socket.socket,
                        client_address: tuple[str, int]) -> None:
        request.settimeout(SOCKET_TIMEOUT_SECONDS)
        if not self._handler_slots.acquire(blocking=False):
            self._reject_overload(request)
            return
        with self._active_lock:
            self._active_handlers += 1
        try:
            super().process_request(request, client_address)
        except Exception:
            with self._active_lock:
                self._active_handlers -= 1
            self._handler_slots.release()
            raise

    def process_request_thread(self, request: socket.socket,
                               client_address: tuple[str, int]) -> None:
        try:
            super().process_request_thread(request, client_address)
        finally:
            with self._active_lock:
                self._active_handlers -= 1
            self._handler_slots.release()

    def _reject_overload(self, request: socket.socket) -> None:
        body = json.dumps({"error": "dashboard is busy; retry shortly"}).encode("utf-8")
        response = (
            b"HTTP/1.1 503 Service Unavailable\r\n"
            b"Content-Type: application/json; charset=utf-8\r\n"
            + f"Content-Length: {len(body)}\r\n".encode("ascii")
            + b"Cache-Control: no-store\r\nConnection: close\r\n\r\n"
            + body
        )
        try:
            request.sendall(response)
        except OSError:
            pass
        finally:
            self.shutdown_request(request)


class DashboardHandler(BaseHTTPRequestHandler):
    server_version = "vodpipe"
    pipeline: Pipeline
    config: Config
    artifacts: ArtifactRegistry
    socket_timeout_seconds = SOCKET_TIMEOUT_SECONDS
    header_deadline_seconds = HEADER_DEADLINE_SECONDS
    body_deadline_seconds = BODY_DEADLINE_SECONDS

    # -- plumbing ----------------------------------------------------------

    def setup(self) -> None:
        self._deadline_lock = threading.Lock()
        self._deadline_generation = 0
        self._deadline_timer: threading.Timer | None = None
        self._oversized_body = False
        self.request.settimeout(self.socket_timeout_seconds)
        super().setup()

    def handle_one_request(self) -> None:
        self._arm_deadline(self.header_deadline_seconds)
        try:
            super().handle_one_request()
        finally:
            self._cancel_deadline()

    def parse_request(self) -> bool:
        parsed = super().parse_request()
        if parsed:
            self._arm_deadline(self.body_deadline_seconds)
        return parsed

    def _arm_deadline(self, seconds: float) -> None:
        with self._deadline_lock:
            self._deadline_generation += 1
            generation = self._deadline_generation
            if self._deadline_timer is not None:
                self._deadline_timer.cancel()
            self.connection.settimeout(min(self.socket_timeout_seconds, seconds))
            timer = threading.Timer(seconds, self._expire_deadline,
                                    args=(generation,))
            timer.daemon = True
            self._deadline_timer = timer
            timer.start()

    def _cancel_deadline(self) -> None:
        with self._deadline_lock:
            self._deadline_generation += 1
            if self._deadline_timer is not None:
                self._deadline_timer.cancel()
                self._deadline_timer = None

    def _expire_deadline(self, generation: int) -> None:
        with self._deadline_lock:
            if generation != self._deadline_generation:
                return
            self.close_connection = True
            try:
                self.connection.shutdown(socket.SHUT_RDWR)
            except OSError:
                pass

    def log_message(self, format: str, *args: Any) -> None:
        LOG.debug("http %s", format % args)

    def _send(self, status: int, body: bytes, content_type: str) -> None:
        try:
            self.send_response(status)
            self.send_header("Content-Type", content_type)
            self.send_header("Content-Length", str(len(body)))
            self.send_header("Cache-Control", "no-store")
            if self.close_connection:
                self.send_header("Connection", "close")
            # A page in another tab must not be able to frame this dashboard and
            # drive it through clickjacking; it has no authentication of its own.
            self.send_header("X-Frame-Options", "DENY")
            self.send_header("Content-Security-Policy",
                             "frame-ancestors 'none'; default-src 'self'")
            self.send_header("Referrer-Policy", "no-referrer")
            self.send_header("X-Content-Type-Options", "nosniff")
            self.end_headers()
            self.wfile.write(body)
            if self._oversized_body:
                self.wfile.flush()
                self.connection.shutdown(socket.SHUT_WR)
        except OSError:
            self.close_connection = True

    def _check_origin(self) -> None:
        """Reject cross-site state-changing requests.

        Any web page the user visits can POST to localhost. Without an Origin
        check, a malicious page could start recordings, rewrite paths, or queue
        expensive work. Requests carrying no Origin at all are allowed through so
        curl and the CLI still work; browsers always send one on cross-site POSTs.
        """
        origin = self.headers.get("Origin")
        if origin:
            host = urlparse(origin).hostname
            if host not in ALLOWED_HOSTS:
                raise ApiError(f"cross-origin request from {origin} refused",
                               HTTPStatus.FORBIDDEN)

        self._check_host()

    def _check_host(self) -> None:
        """Blocks DNS-rebinding, where an attacker hostname resolves to 127.0.0.1."""
        host_header = (self.headers.get("Host") or "").rsplit(":", 1)[0].strip("[]")
        if host_header and host_header not in ALLOWED_HOSTS:
            raise ApiError(f"unexpected Host header {host_header!r}",
                           HTTPStatus.FORBIDDEN)

    def _require_json(self) -> None:
        content_type = (self.headers.get("Content-Type") or "").split(";")[0].strip()
        if content_type.lower() != "application/json":
            # Simple-request content types are the ones a cross-site form can
            # send without triggering a preflight, so requiring JSON is itself
            # part of the CSRF defence.
            raise ApiError("Content-Type must be application/json",
                           HTTPStatus.UNSUPPORTED_MEDIA_TYPE)

    def _json(self, payload: Any, status: int = HTTPStatus.OK) -> None:
        self._send(status, json.dumps(payload, ensure_ascii=False).encode("utf-8"),
                   "application/json; charset=utf-8")

    def _body(self) -> dict[str, Any]:
        raw_length = self.headers.get("Content-Length")
        try:
            length = int(raw_length or 0)
        except ValueError:
            raise ApiError("Content-Length is not a number")
        if length < 0:
            # read(-1) would block until the peer closes, pinning a thread.
            raise ApiError("Content-Length must not be negative")
        if length > MAX_BODY_BYTES:
            # Never drain attacker-controlled bytes on an admitted handler. Send
            # the JSON 413 immediately. Half-closing reads first prevents Windows
            # from resetting away the response body because upload bytes remain.
            self.close_connection = True
            self._oversized_body = True
            try:
                self.connection.shutdown(socket.SHUT_RD)
            except OSError:
                pass
            raise ApiError(f"request body exceeds {MAX_BODY_BYTES} bytes",
                           HTTPStatus.REQUEST_ENTITY_TOO_LARGE)
        if not length:
            return {}

        raw = self.rfile.read(length)
        if len(raw) < length:
            raise ApiError("request body ended early")
        try:
            value = json.loads(raw.decode("utf-8"))
        except UnicodeDecodeError:
            # A malformed body is the client's mistake, not a server fault; this
            # used to escape as an unhandled 500.
            raise ApiError("request body is not valid UTF-8")
        except json.JSONDecodeError:
            raise ApiError("request body is not valid JSON")
        if not isinstance(value, dict):
            raise ApiError("request body must be a JSON object")
        return value

    # -- routing -----------------------------------------------------------

    def do_GET(self) -> None:
        parsed = urlparse(self.path)
        route = parsed.path
        query = parse_qs(parsed.query)
        try:
            # AUD2-022: Host was checked on POST only, so a DNS-rebound page
            # could still GET session metadata, transcripts and rundowns. The
            # check costs nothing and belongs on every route.
            self._check_host()
            if route.startswith("/api/"):
                self._json(self._get_route(route, query))
            else:
                self._serve_static(route)
        except ApiError as exc:
            self._json({"error": str(exc)}, exc.status)
        except (TimeoutError, ConnectionError):
            self.close_connection = True
        except Exception:
            # The detail goes to the log, not to the browser: exception text here
            # has carried absolute paths and provider messages.
            LOG.exception("GET %s failed", route)
            self._json({"error": "internal error -- see the server log"},
                       HTTPStatus.INTERNAL_SERVER_ERROR)

    def do_POST(self) -> None:
        route = urlparse(self.path).path
        try:
            self._check_origin()
            self._require_json()
            payload = self._post_route(route, self._body())
            # A handler may ask for a status other than 200 -- accepted work in
            # particular, which is queued rather than done when we answer.
            if isinstance(payload, tuple):
                payload, status = payload
                self._json(payload, status)
            else:
                self._json(payload)
        except ApiError as exc:
            self._json({"error": str(exc)}, exc.status)
        except (TimeoutError, ConnectionError):
            self.close_connection = True
        except Exception:
            # The detail goes to the log, not to the browser: exception text here
            # has carried absolute paths and provider messages.
            LOG.exception("POST %s failed", route)
            self._json({"error": "internal error -- see the server log"},
                       HTTPStatus.INTERNAL_SERVER_ERROR)

    def _get_route(self, route: str, query: dict[str, list[str]]) -> Any:
        if route == "/api/state":
            return self.pipeline.state_payload()
        if route == "/api/config":
            return self.config.redacted()
        if route == "/api/session":
            session = self._session(self._one(query, "session_id"))
            return session.to_dict()
        if route == "/api/outputs":
            return self._outputs(self._one(query, "session_id"),
                                 self._one(query, "chunk", required=False))
        if route == "/api/file":
            return {"text": self._read_artifact(
                self._one(query, "artifact_id"))}
        raise ApiError(f"unknown endpoint {route}", HTTPStatus.NOT_FOUND)

    def _post_route(self, route: str, body: dict[str, Any]) -> Any:
        handlers: dict[str, Callable[[dict[str, Any]], Any]] = {
            "/api/channels/add": self._add_channel,
            "/api/channels/remove": self._remove_channel,
            "/api/channels/settings": self._channel_settings,
            "/api/record/start": self._start,
            "/api/record/stop": self._stop,
            "/api/vod/download": self._vod_download,
            "/api/vod/stop": self._vod_stop,
            "/api/snapshot": self._snapshot,
            "/api/chunk/retranscribe": self._retranscribe,
            "/api/chunk/summarize": self._summarize,
            "/api/chunk/edit": self._edit,
            "/api/config": self._save_config,
            "/api/reveal": self._reveal,
        }
        handler = handlers.get(route)
        if handler is None:
            raise ApiError(f"unknown endpoint {route}", HTTPStatus.NOT_FOUND)
        return handler(body)

    # -- handlers ----------------------------------------------------------

    @staticmethod
    def _text_field(body: dict[str, Any], key: str) -> str:
        value = body.get(key, "")
        if not isinstance(value, str):
            raise ApiError(f"{key} must be text")
        return value

    def _add_channel(self, body: dict[str, Any]) -> Any:
        try:
            channel = self.pipeline.add_channel(self._text_field(body, "name"))
        except (InvalidChannel, ValueError) as exc:
            raise ApiError(str(exc))
        return {"ok": True, "channel": channel}

    def _remove_channel(self, body: dict[str, Any]) -> Any:
        try:
            self.pipeline.remove_channel(self._text_field(body, "name"))
        except (InvalidChannel, ValueError) as exc:
            raise ApiError(str(exc))
        return {"ok": True}

    def _channel_settings(self, body: dict[str, Any]) -> Any:
        try:
            channel = parse_channel(self._text_field(body, "name"))
        except InvalidChannel as exc:
            raise ApiError(str(exc))
        for key in ("auto_record",):
            if key in body:
                self.pipeline.set_channel_setting(channel, key, _flag(body[key]))
        return {"ok": True}

    def _start(self, body: dict[str, Any]) -> Any:
        try:
            channel = parse_channel(self._text_field(body, "channel"))
        except InvalidChannel as exc:
            raise ApiError(str(exc))
        # "already recording" and "below the free-space floor" are answers, not
        # crashes; report them as such instead of a 500 with a stack trace.
        try:
            outcome = self.pipeline.request_recording(channel)
        except RuntimeError as exc:
            raise ApiError(str(exc), HTTPStatus.CONFLICT)
        # An offline channel is armed rather than started, so the answer says
        # which of the two happened instead of implying a recording began.
        if outcome["state"] == "armed":
            return ({"ok": True, **outcome}, HTTPStatus.ACCEPTED)
        return {"ok": True, **outcome}

    def _stop(self, body: dict[str, Any]) -> Any:
        """Stops a recording, or cancels one that is waiting for the channel."""
        try:
            self.pipeline.stop_recording(self._text_field(body, "channel"))
        except (InvalidChannel, RuntimeError, ValueError) as exc:
            raise ApiError(str(exc), HTTPStatus.CONFLICT)
        return {"ok": True}

    def _vod_download(self, body: dict[str, Any]) -> Any:
        """Start downloading a Twitch VOD through the full pipeline."""
        url = self._text_field(body, "url").strip()
        if not url:
            raise ApiError("a VOD URL or numeric id is required")
        start = _optional_float(body.get("start"))
        duration = _optional_float(body.get("duration"))
        if start is not None and start < 0:
            raise ApiError("start must be zero or a positive number of seconds")
        if duration is not None and duration <= 0:
            raise ApiError("duration must be a positive number of seconds")
        try:
            session = self.pipeline.download_vod(
                url, start=start, duration=duration)
        except RuntimeError as exc:
            raise ApiError(str(exc), HTTPStatus.CONFLICT)
        return ({"ok": True, "session_id": session.session_id,
                 "channel": session.channel, "directory": session.directory},
                HTTPStatus.ACCEPTED)

    def _vod_stop(self, body: dict[str, Any]) -> Any:
        """Stop an in-progress VOD download; the chunks so far are kept."""
        session_id = self._text_field(body, "session_id").strip()
        if not session_id:
            raise ApiError("session_id is required")
        try:
            self.pipeline.stop_vod(session_id)
        except RuntimeError as exc:
            raise ApiError(str(exc), HTTPStatus.CONFLICT)
        return {"ok": True}

    def _snapshot(self, body: dict[str, Any]) -> Any:
        session_id = str(body.get("session_id", "")).strip()
        if not session_id:
            raise ApiError("session_id is required")

        raw_name = body.get("name", "")
        if not isinstance(raw_name, str):
            raise ApiError("snapshot name must be text")
        name_units = _windows_units(raw_name)
        if name_units > MAX_SNAPSHOT_NAME_UNITS:
            raise ApiError(
                f"snapshot name is too long (maximum "
                f"{MAX_SNAPSHOT_NAME_UNITS} characters)")

        # Recovered manifests may predate today's session-id validation. Check
        # the actual fixed prefix too, so even those cannot exceed MAX_PATH's
        # per-component filename limit after the worker appends clocks and a token.
        session = self.pipeline.store.get(session_id)
        if session is not None:
            label = slugify(raw_name) if raw_name else "snap"
            fixed_units = _windows_units(
                f"{session.channel}_{session.session_id}_") + SNAPSHOT_SUFFIX_RESERVE
            if fixed_units + _windows_units(label) > WINDOWS_FILENAME_UNITS:
                available = max(0, WINDOWS_FILENAME_UNITS - fixed_units)
                raise ApiError(
                    "snapshot name is too long for a Windows filename "
                    f"(maximum {min(MAX_SNAPSHOT_NAME_UNITS, available)} "
                    "characters for this session)")

        request = SnapshotRequest(
            session_id=session_id,
            last_minutes=_optional_float(body.get("last_minutes")),
            start=_optional_float(body.get("start")),
            end=_optional_float(body.get("end")),
            precise=_flag(body.get("precise"), False),
            transcribe=_flag(body.get("transcribe"), True),
            name=raw_name,
        )
        if request.last_minutes is None and request.start is None:
            raise ApiError("give either last_minutes or a start/end range")
        # P9: reject non-positive ranges at admission rather than deep in ffmpeg
        # geometry. A zero/negative window is a client mistake, not a 500.
        if request.last_minutes is not None and request.last_minutes <= 0:
            raise ApiError("last_minutes must be a positive number")
        if request.start is not None and request.start < 0:
            raise ApiError("start must be zero or a positive number of seconds")
        if (request.end is not None and request.start is not None
                and request.end <= request.start):
            raise ApiError("end must be after start")

        # Queued, not cut here. ffprobe and ffmpeg on the HTTP thread held the
        # request open for the length of an encode and gave the browser no way to
        # show progress; worse, nothing bounded how many a user could start.
        try:
            job = self.pipeline.queue_snapshot(request)
        except (RuntimeError, ValueError) as exc:
            raise ApiError(str(exc), HTTPStatus.CONFLICT)
        return ({"ok": True, "queued": True, "job": job.key, "label": job.label},
                HTTPStatus.ACCEPTED)

    def _accepted(self, job: Any, what: str) -> Any:
        """AUD2-058: only report work as queued if the pool actually took it.

        `JobRunner.submit()` returns None when an identical job is already
        queued or running, or when the pool is draining. Ignoring that returned
        202 {"queued": true} for work that did not exist, so the dashboard
        confirmed a re-transcription that was never going to happen.
        """
        if job is None:
            raise ApiError(
                f"{what} is already queued or the queue is shutting down",
                HTTPStatus.CONFLICT)
        return ({"ok": True, "queued": True, "job": job.key},
                HTTPStatus.ACCEPTED)

    def _retranscribe(self, body: dict[str, Any]) -> Any:
        session, chunk = self._session_chunk(body)
        # "still recording", "no key", "no media" are answers the user can act on.
        try:
            job = self.pipeline.retranscribe(session, chunk)
        except RuntimeError as exc:
            raise ApiError(str(exc), HTTPStatus.CONFLICT)
        return self._accepted(job, "this transcript")

    def _summarize(self, body: dict[str, Any]) -> Any:
        session, chunk = self._session_chunk(body)
        try:
            job = self.pipeline.resummarize(session, chunk)
        except RuntimeError as exc:
            raise ApiError(str(exc), HTTPStatus.CONFLICT)
        return self._accepted(job, "this rundown")

    def _edit(self, body: dict[str, Any]) -> Any:
        session, chunk = self._session_chunk(body)
        try:
            job = self.pipeline.recut(session, chunk)
        except RuntimeError as exc:
            raise ApiError(str(exc), HTTPStatus.CONFLICT)
        return self._accepted(job, "this edited cut")

    def _save_config(self, body: dict[str, Any]) -> Any:
        if not isinstance(body, dict):
            raise ApiError("expected a config object")
        # Channels are managed through their own endpoints; ignore them here so a
        # settings save can never clobber the watch list.
        body.pop("channels", None)
        try:
            # One transaction: memory and disk change together or not at all.
            # Applying and then saving separately left a failed write with the
            # change live in memory but absent from the file it reloads from.
            self.config.apply_and_save(body)
        except ConfigError as exc:
            # Nothing was changed: apply_and_save() validates before assigning.
            raise ApiError(str(exc))
        except OSError:
            LOG.exception("could not save dashboard configuration")
            raise ApiError("could not save the configuration; see the server log",
                           HTTPStatus.INTERNAL_SERVER_ERROR)
        return {"ok": True, "config": self.config.redacted()}

    def _reveal(self, body: dict[str, Any]) -> Any:
        artifact_id = body.get("artifact_id")
        if artifact_id:
            target = self._resolve_artifact(str(artifact_id))
        else:
            target = self._safe_path(str(body.get("path", "")))
        if os.name != "nt":
            raise ApiError("reveal is only wired up for Windows Explorer")
        if target.is_dir():
            subprocess.Popen(["explorer", str(target)])
        else:
            subprocess.Popen(["explorer", "/select,", str(target)])
        return {"ok": True}

    # -- helpers -----------------------------------------------------------

    def _one(self, query: dict[str, list[str]], key: str,
             required: bool = True) -> str:
        values = query.get(key) or []
        if not values:
            if required:
                raise ApiError(f"{key} is required")
            return ""
        return values[0]

    def _session(self, session_id: str):
        session = self.pipeline.store.get(session_id)
        if session is None:
            raise ApiError(f"unknown session {session_id}", HTTPStatus.NOT_FOUND)
        return session

    def _session_chunk(self, body: dict[str, Any]):
        session = self._session(str(body.get("session_id", "")))
        label = str(body.get("chunk", ""))
        for chunk in session.chunks:
            if chunk.label == label or str(chunk.index) == label:
                return session, chunk
        raise ApiError(f"unknown chunk {label}", HTTPStatus.NOT_FOUND)

    def _outputs(self, session_id: str, chunk_label: str = "") -> Any:
        session = self._session(session_id)
        root = session.path
        groups: list[dict[str, Any]] = []

        targets: list[tuple[str, Path, frozenset[str]]] = []
        if chunk_label:
            # Resolved through the session's own chunks, never by joining the
            # caller's text onto a path: `?chunk=../../..` would otherwise
            # enumerate arbitrary directories.
            match = next((chunk for chunk in session.chunks
                          if chunk.label == chunk_label), None)
            if match is None:
                raise ApiError(f"unknown chunk {chunk_label}", HTTPStatus.NOT_FOUND)
            targets.append(("transcript", root / "transcripts" / match.label,
                            TRANSCRIPT_OUTPUT_NAMES))
            edited = root / "transcripts" / match.label / "edited"
            if edited.is_dir():
                targets.append(("edited cut", edited, TRANSCRIPT_OUTPUT_NAMES))
        else:
            for chunk in sorted(session.chunks, key=lambda item: item.index):
                targets.append((chunk.label, root / "transcripts" / chunk.label,
                                TRANSCRIPT_OUTPUT_NAMES))
            targets.append(("snapshots", root / "snapshots",
                            SNAPSHOT_OUTPUT_NAMES))
            # Snapshot transcripts live in their own nested folders; without this
            # a finished snapshot transcript never appeared in the dashboard.
            for child in self._snapshot_transcript_dirs(session):
                targets.append((f"snapshot: {child.name}", child,
                                TRANSCRIPT_OUTPUT_NAMES))
            # The edited cut carries its own export set, in its own directory,
            # so text-based editing works against the file that was cut rather
            # than only against the master it came from.
            for chunk in sorted(session.chunks, key=lambda item: item.index):
                edited = root / "transcripts" / chunk.label / "edited"
                if edited.is_dir():
                    targets.append((f"{chunk.label}: edited cut", edited,
                                    TRANSCRIPT_OUTPUT_NAMES))
            targets.append(("session", root, SESSION_OUTPUT_NAMES))

        for name, directory, allowed_names in targets:
            files = []
            for filename in sorted(allowed_names):
                path = directory / filename
                registered = self._register_artifact(session, path)
                if registered is None:
                    continue
                artifact_id, _, stat = registered
                files.append({
                    "name": filename,
                    "artifact_id": artifact_id,
                    "size": stat.st_size,
                    "modified": stat.st_mtime,
                })
            if files:
                groups.append({"group": name, "files": files})
        return {"groups": groups}

    def _snapshot_transcript_dirs(self, session: Any) -> list[Path]:
        """Derive snapshot transcript folders from the server-written index."""
        index = session.path / "snapshots" / "snapshots.json"
        registered = self._register_artifact(session, index)
        if registered is None:
            return []
        _, target, stat = registered
        try:
            if stat.st_size > MAX_READABLE_BYTES:
                return []
            entries = json.loads(target.read_text(encoding="utf-8"))
        except (OSError, json.JSONDecodeError):
            return []
        if not isinstance(entries, list):
            return []

        directories = set()
        for entry in entries:
            if not isinstance(entry, dict):
                continue
            filename = entry.get("file")
            if not isinstance(filename, str) or not _plain_filename(filename):
                continue
            if Path(filename).suffix.lower() != ".mp4":
                continue
            directories.add(index.parent / f"{Path(filename).stem}_transcript")
        return sorted(directories)

    def _register_artifact(self, session: Any,
                           path: Path) -> tuple[str, Path, os.stat_result] | None:
        try:
            masters = self.pipeline.config.masters_root.resolve(strict=True)
            root = session.path.resolve(strict=True)
            target = path.resolve(strict=True)
            if not _within(root, masters) or not _within(target, root):
                return None
            if not target.is_file() or path.suffix.lower() not in READABLE_SUFFIXES:
                return None
            stat = target.stat()
        except OSError:
            return None
        if stat.st_size > MAX_READABLE_BYTES:
            return None
        artifact_id = self.artifacts.register(session.session_id, path, target)
        return artifact_id, target, stat

    def _safe_path(self, raw: str) -> Path:
        if not raw:
            raise ApiError("path is required")
        target = Path(raw).resolve()
        root = self.pipeline.config.masters_root
        if root not in target.parents and target != root:
            raise ApiError("path is outside the masters root", HTTPStatus.FORBIDDEN)
        if not target.exists():
            raise ApiError("no such file", HTTPStatus.NOT_FOUND)
        return target

    def _resolve_artifact(self, artifact_id: str) -> Path:
        if not artifact_id:
            raise ApiError("artifact_id is required")
        registered = self.artifacts.get(artifact_id)
        if registered is None:
            raise ApiError("unknown artifact", HTTPStatus.NOT_FOUND)
        session = self.pipeline.store.get(registered.session_id)
        if session is None:
            raise ApiError("unknown artifact", HTTPStatus.NOT_FOUND)
        try:
            masters = self.pipeline.config.masters_root.resolve(strict=True)
            root = session.path.resolve(strict=True)
            target = registered.path.resolve(strict=True)
        except OSError:
            raise ApiError("artifact no longer exists", HTTPStatus.NOT_FOUND)
        if (target != registered.resolved or not _within(root, masters)
                or not _within(target, root) or not target.is_file()):
            raise ApiError("artifact path is no longer safe", HTTPStatus.FORBIDDEN)
        return target

    def _read_artifact(self, artifact_id: str) -> str:
        target = self._resolve_artifact(artifact_id)
        if target.suffix.lower() not in READABLE_SUFFIXES:
            raise ApiError("that file type is not previewable", HTTPStatus.FORBIDDEN)
        if target.stat().st_size > MAX_READABLE_BYTES:
            raise ApiError("file is too large to preview")
        return target.read_text(encoding="utf-8", errors="replace")

    def _serve_static(self, route: str) -> None:
        name = "index.html" if route in ("/", "") else route.lstrip("/")
        target = (STATIC_DIR / name).resolve()
        if STATIC_DIR not in target.parents or not target.is_file():
            self._send(HTTPStatus.NOT_FOUND, b"not found", "text/plain")
            return
        content_type = mimetypes.guess_type(target.name)[0] or "application/octet-stream"
        if content_type.startswith("text/") or content_type.endswith("javascript"):
            content_type += "; charset=utf-8"
        self._send(HTTPStatus.OK, target.read_bytes(), content_type)


def _optional_float(value: Any) -> float | None:
    """A finite number, or None. NaN and infinity poison every geometry check."""
    if value is None or value == "":
        return None
    if isinstance(value, bool) or not isinstance(value, (int, float, str)):
        raise ApiError(f"expected a number, got {value!r}")
    try:
        result = float(value)
    except (TypeError, ValueError):
        raise ApiError(f"expected a number, got {value!r}")
    if math.isnan(result) or math.isinf(result):
        raise ApiError("numbers must be finite")
    return result


def _flag(value: Any, default: bool = False) -> bool:
    """Strict boolean. `bool("false")` is True, which silently inverted flags."""
    if value is None:
        return default
    if isinstance(value, bool):
        return value
    raise ApiError(f"expected true or false, got {value!r}")


def _within(path: Path, root: Path) -> bool:
    try:
        path.relative_to(root)
        return True
    except ValueError:
        return False


def _plain_filename(value: str) -> bool:
    path = Path(value)
    return bool(value) and not path.is_absolute() and path.name == value \
        and value not in (".", "..")


def _windows_units(value: str) -> int:
    return len(value.encode("utf-16-le", errors="surrogatepass")) // 2


def serve(pipeline: Pipeline, config: Config, *, port: int | None = None,
          open_browser: bool | None = None,
          max_handlers: int = MAX_CONCURRENT_HANDLERS,
          socket_timeout: float = SOCKET_TIMEOUT_SECONDS,
          header_deadline: float = HEADER_DEADLINE_SECONDS,
          body_deadline: float = BODY_DEADLINE_SECONDS) -> BoundedThreadingHTTPServer:
    """Start the dashboard.

    `port` and `open_browser` are per-run overrides and are deliberately not written
    back into the config: a one-off `--port` flag must not become the stored default
    the next time something saves settings.
    """
    host = config.get("dashboard.host", "127.0.0.1")
    port = int(port if port is not None else config.get("dashboard.port", 8420))

    artifacts = ArtifactRegistry()
    handler = type("BoundHandler", (DashboardHandler,), {
        "pipeline": pipeline,
        "config": config,
        "artifacts": artifacts,
        "socket_timeout_seconds": float(socket_timeout),
        "header_deadline_seconds": float(header_deadline),
        "body_deadline_seconds": float(body_deadline),
    })
    httpd = BoundedThreadingHTTPServer(
        (host, port), handler, max_handlers=max_handlers)

    url = f"http://{host}:{port}/"
    LOG.info("dashboard on %s", url)
    if open_browser if open_browser is not None else config.get("dashboard.open_browser", True):
        timer = threading.Timer(1.0, lambda: webbrowser.open(url))
        timer.daemon = True
        timer.start()
    return httpd
