"""Generate the compile-time inputs of `VODPipeline.exe`.

Two things the Windows host cannot be allowed to carry as literals, because
both of them went stale exactly the way literals do:

* **the icons**, regenerated from `docs/logo.png` by `make_icons.py`. Replacing
  the logo used to change the README and nothing else.
* **the version**, written to `version.g.cs` from `vodpipe.__version__`. It was
  hardcoded in `host.cs` as `1.0.0` and stayed there through 1.0.1, so Apps &
  Features and the exe's own properties both reported a version the project had
  already left behind.

Run by `packaging/build.cmd` and by `vodpipe install` before every compile.
Nothing here is shipped in the wheel; it is build tooling.
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
PACKAGING = ROOT / "packaging"
VERSION_CS = PACKAGING / "version.g.cs"

TEMPLATE = """\
// Generated by packaging/prebuild.py from vodpipe/__init__.py. Do not edit.
using System.Reflection;

[assembly: AssemblyVersion("{four}")]
[assembly: AssemblyFileVersion("{four}")]
[assembly: AssemblyInformationalVersion("{version}")]

internal static class BuildInfo
{{
    public const string Version = "{version}";
}}
"""


def package_version() -> str:
    """`__version__` read as text, so this never imports the package.

    A build tool that imports `vodpipe` would drag the whole package (and its
    tool discovery) into a step whose only job is to write eleven lines of C#.
    """
    source = (ROOT / "vodpipe" / "__init__.py").read_text(encoding="utf-8")
    found = re.search(r'^__version__\s*=\s*"([^"]+)"', source, re.MULTILINE)
    if not found:
        raise RuntimeError("vodpipe/__init__.py has no __version__")
    return found.group(1)


def four_part(version: str) -> str:
    """`1.0.2` -> `1.0.2.0`. Win32 VERSIONINFO wants four numeric parts."""
    parts = [p for p in re.split(r"[.\-+]", version) if p.isdigit()][:4]
    while len(parts) < 4:
        parts.append("0")
    return ".".join(parts)


def write_version() -> str:
    version = package_version()
    text = TEMPLATE.format(version=version, four=four_part(version))
    # Only rewrite on a change: the file is a build input, and touching it
    # every run would make `ensure_host` recompile every run.
    if not VERSION_CS.is_file() or VERSION_CS.read_text(encoding="utf-8") != text:
        VERSION_CS.write_text(text, encoding="utf-8")
    return version


def main() -> int:
    sys.path.insert(0, str(PACKAGING))
    import make_icons

    version = write_version()
    print(f"version {version} -> {VERSION_CS.relative_to(ROOT)}")
    return make_icons.main()


if __name__ == "__main__":
    raise SystemExit(main())
