// Generated by packaging/prebuild.py from vodpipe/__init__.py. Do not edit.
using System.Reflection;

[assembly: AssemblyVersion("1.1.0.0")]
[assembly: AssemblyFileVersion("1.1.0.0")]
[assembly: AssemblyInformationalVersion("1.1.0")]

internal static class BuildInfo
{
    public const string Version = "1.1.0";
}
